--STEP 1 CREATING THE SCHEMA --
-- CREATE SCHEMA  REPORT_SCHEMA--
--STEP 2 EXTRACTING THE DATA NEEDED FOR THE DAILY AGGREGATE TABLE__
WITH CTE_RENTALS_PER_DAY AS 
							
(
    SELECT 
        CAST(RENTAL_DETAIL.rental_date AS DATE) AS rental_day,
        COUNT(RENTAL_DETAIL.rental_id) AS total_rentals,
        COALESCE(SUM(PAYMENT_DETAIL.amount), 0) AS total_amount
    FROM
		public.rental AS RENTAL_DETAIL
    LEFT OUTER JOIN 
		public.payment AS PAYMENT_DETAIL
    ON 
		PAYMENT_DETAIL.rental_id = RENTAL_DETAIL.rental_id
    GROUP BY CAST
		(RENTAL_DETAIL.rental_date AS DATE)
    
),
CTE_RETURNS_PER_DAY AS
(
	SELECT 
		CAST(RENTAL_DETAIL.return_date AS DATE) AS return_day,
		COUNT(RENTAL_DETAIL.rental_id) AS total_returns
	FROM 
		public.rental AS RENTAL_DETAIL
 	WHERE 
		RENTAL_DETAIL.return_date IS NOT NULL
	GROUP BY
		CAST(RENTAL_DETAIL.return_date AS DATE)
	
),
CTE_RENTAL_DIFFERENCE AS (
	SELECT
		 rental_day,
		 COALESCE(CTE_RENTALS_PER_DAY.TOTAL_RENTALS - LAG(CTE_RENTALS_PER_DAY.TOTAL_RENTALS) 
		     OVER (ORDER BY CTE_RENTALS_PER_DAY.RENTAL_DAY), 0) AS RENTAL_DIFFERENCE
	FROM
		CTE_RENTALS_PER_DAY
	
),

CTE_TOTAL_CUSTOMERS AS
(
    SELECT
        CAST(RENTAL_DETAIL.rental_date AS DATE) AS rental_day,
        COUNT(DISTINCT RENTAL_DETAIL.customer_id) AS total_customers
    FROM 
		public.rental AS RENTAL_DETAIL
    GROUP BY 
		CAST(RENTAL_DETAIL.rental_date AS DATE)
    
),
CTE_DIFFERENCE_CUSTOMERS AS
(
    SELECT
        rental_day,
        COALESCE(total_customers - LAG(total_customers) 
		  OVER (ORDER BY rental_day),0 )AS customer_difference
    FROM 
		CTE_TOTAL_CUSTOMERS
),

CTE_AVERAGE_RENTAL_DURATION AS 
(
    SELECT 
        CAST(RENTAL_DETAIL.rental_date AS DATE) AS rental_day,
        ROUND(COALESCE (AVG(( CAST(RENTAL_DETAIL.reTURN_date AS DATE) - CAST(RENTAL_DETAIL.rental_date AS DATE))),0),2) AS avg_rental_duration
    FROM 
		public.rental AS RENTAL_DETAIL
    GROUP BY 
        CAST(RENTAL_DETAIL.rental_date AS DATE)
	
),
CTE_AVERAGE_RENTALS_PER_CUSTOMER AS
(
    SELECT
        CAST(RENTAL_DETAIL.rental_date AS DATE) AS rental_day,
        ROUND(COUNT(RENTAL_DETAIL.rental_id) * 1.0 / COUNT(DISTINCT RENTAL_DETAIL.customer_id), 2) AS avg_rentals_per_customer
    FROM 
		public.rental AS RENTAL_DETAIL
    GROUP BY CAST(RENTAL_DETAIL.rental_date AS DATE)
   
),

CTE_MOVING_AVERAGES AS 
(
    SELECT
        rental_day,
       ROUND((avg(avg_rentals_per_customer) OVER (ORDER BY rental_day) ),2) AS MOVING_AVERAGE
    FROM
		CTE_AVERAGE_RENTALS_PER_CUSTOMER
),

CTE_DAY_NAME_INDEX AS
(
    SELECT
        rental_day,
        TO_CHAR(rental_day, 'Day') AS day_name
    FROM 
		CTE_RENTALS_PER_DAY
),
CTE_daily_unpaid_rentals AS (
    SELECT
	
        CAST(RENTAL_DETAIL.rental_date AS DATE) AS RENTAL_day,
       COALESCE(COUNT(RENTAL_DETAIL.rental_id),0)  AS total_unpaid_rentals
    FROM 
		PUBLIC.rental AS RENTAL_DETAIL
    LEFT JOIN 
		PUBLIC.payment AS PAYMENT_DETAIL
    ON 
		payment_DETAIL.rental_id = rental_DETAIL.rental_id
    WHERE 
		PAYMENT_DETAIL.RENTAL_ID IS NULL
    GROUP BY
        CAST(RENTAL_DETAIL.rental_date AS DATE)	
),
CTE_DAILY_AVERAGE_REVENUE_PER_CUSTOMER AS
(
    SELECT
        CTE_RENTALS_PER_DAY.RENTAL_DAY,
        ROUND( COALESCE(
            (CTE_RENTALS_PER_DAY.TOTAL_AMOUNT * 1.0) / NULLIF(CTE_TOTAL_CUSTOMERS.total_customers, 0),
            0),2)
              AS DAILY_AVERAGE_REVENUE_PER_CUSTOMER
    FROM 
		CTE_RENTALS_PER_DAY
    INNER JOIN 
		CTE_TOTAL_CUSTOMERS ON CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_TOTAL_CUSTOMERS.RENTAL_DAY
),

CTE_REVENUE_DIFFERENCE AS (
	SELECT
		 rental_day,
		 COALESCE(CTE_RENTALS_PER_DAY.TOTAL_AMOUNT - LAG(CTE_RENTALS_PER_DAY.TOTAL_AMOUNT) 
		     OVER (ORDER BY CTE_RENTALS_PER_DAY.RENTAL_DAY), 0) AS REVENUE_DIFFERENCE
	FROM
		CTE_RENTALS_PER_DAY
	
),
CTE_PAID_RENTALS AS (

SELECT  CTE_RENTALS_PER_DAY.RENTAL_DAY ,
COALESCE(TOTAL_RENTALS-COALESCE(CTE_daily_unpaid_rentals.total_unpaid_rentals, 0),0)  AS PAYED_RENTALS
FROM CTE_RENTALS_PER_DAY
LEFT JOIN CTE_daily_unpaid_rentals ON CTE_daily_unpaid_rentals.RENTAL_DAY= CTE_RENTALS_PER_DAY.RENTAL_DAY



),

DAILY_REPORT AS ( 

SELECT
    CTE_RENTALS_PER_DAY.RENTAL_DAY,
    DAY_NAME,
    CTE_RENTALS_PER_DAY.TOTAL_RENTALS,
    CTE_RENTAL_DIFFERENCE.RENTAL_DIFFERENCE,
    CTE_TOTAL_CUSTOMERS.total_customers ,
    CTE_DIFFERENCE_CUSTOMERS.customer_difference,
    CTE_AVERAGE_RENTALS_PER_CUSTOMER.avg_rentals_per_customer,
    CTE_MOVING_AVERAGES.MOVING_AVERAGE,
    CTE_AVERAGE_RENTAL_DURATION.avg_rental_duration,
	CTE_RENTALS_PER_DAY.TOTAL_AMOUNT AS DAILY_REVENUE,
	COALESCE(CTE_daily_unpaid_rentals.total_unpaid_rentals, 0) AS UNPAYED_RENTALS,
    CTE_PAID_RENTALS.PAYED_RENTALS,
	ROUND(COALESCE(( CTE_PAID_RENTALS.PAYED_RENTALS * 100.0) / NULLIF(CTE_RENTALS_PER_DAY.TOTAL_RENTALS, 0), 0), 2) AS PERCENTAGE_OF_PAYED_RENTALS,
    ROUND(COALESCE((CTE_daily_unpaid_rentals.total_unpaid_rentals * 100.0) / NULLIF(CTE_RENTALS_PER_DAY.TOTAL_RENTALS, 0), 0), 2) AS PERCENTAGE_OF_UNPAYED_RENTALS,
	CTE_REVENUE_DIFFERENCE.REVENUE_DIFFERENCE,
    CTE_DAILY_AVERAGE_REVENUE_PER_CUSTOMER.DAILY_AVERAGE_REVENUE_PER_CUSTOMER AS AVERAGE_PAYMENT_PER_CUSTOMER
	
FROM CTE_RENTALS_PER_DAY
LEFT JOIN
		CTE_TOTAL_CUSTOMERS ON CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_TOTAL_CUSTOMERS.RENTAL_DAY
LEFT JOIN 
		CTE_DAY_NAME_INDEX ON CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_DAY_NAME_INDEX.RENTAL_DAY
LEFT JOIN 
		CTE_AVERAGE_RENTALS_PER_CUSTOMER ON CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_AVERAGE_RENTALS_PER_CUSTOMER.RENTAL_DAY
LEFT JOIN 
		CTE_DIFFERENCE_CUSTOMERS ON CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_DIFFERENCE_CUSTOMERS.RENTAL_DAY
LEFT JOIN 
		CTE_MOVING_AVERAGES ON CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_MOVING_AVERAGES.RENTAL_DAY
LEFT JOIN 
		CTE_AVERAGE_RENTAL_DURATION ON CTE_RENTALS_PER_DAY.RENTAL_DAY=  CTE_AVERAGE_RENTAL_DURATION.RENTAL_DAY
LEFT JOIN 
		CTE_daily_unpaid_rentals ON  CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_daily_unpaid_rentals.RENTAL_DAY
LEFT JOIN 
		CTE_DAILY_AVERAGE_REVENUE_PER_CUSTOMER ON CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_DAILY_AVERAGE_REVENUE_PER_CUSTOMER.RENTAL_DAY
LEFT JOIN 
		CTE_RENTAL_DIFFERENCE  ON CTE_RENTALS_PER_DAY.RENTAL_DAY = CTE_RENTAL_DIFFERENCE.RENTAL_DAY
LEFT JOIN 
		CTE_REVENUE_DIFFERENCE ON  CTE_RENTALS_PER_DAY.RENTAL_DAY= CTE_REVENUE_DIFFERENCE.RENTAL_DAY
LEFT JOIN 
		CTE_PAID_RENTALS ON CTE_RENTALS_PER_DAY.RENTAL_DAY= CTE_PAID_RENTALS.RENTAL_DAY)

---------------------------------------------------------------------------------------------------------
--CREATING NEW TABLE AND STORING THE RESULTS IN IT 
-- SELECT *
-- INTO REPORT_SCHEMA.DAILY_AGGREGATE
-- FROM DAILY_REPORT;

---------------------------------------------------------------------------------------------------------

